### ISSUE TITLE
Negative Values Not Validated

### ISSUE THREAD

**Issue by vkku** [tmess567/rentflees#2]
Negative values for x and y coordinates in schema is not validated and hindering the form submission.

```
//Schema.js
XCoordinate: {
    label: "X - Coordinate",
    optional: true,
    type: Number,
    max: 100,
        autoform: {
            type: "hidden"
        }
  },
  YCoordinate: {
    label: "Y - Coordinate",
    optional: true,
    type: Number,
    max: 100,
        autoform: {
            type: "hidden"
        }
  }
```

Changing type to String autoconverts the field to number but form does not clear out.

**Comment by tmess567** [comment]
What's the problem with string, please explain

**Comment by vkku** [comment]
The values in schema should be Number as they're integers but declaring them as Number results in invalid enteries of form hidden entry coordinates.

**Comment by tmess567** [comment]
Use string instead if it works, the large number of decimal place will take as much space anyway.

**Comment by vkku** [comment]
Using String makes the form submit on click but it dosen't gets cleared and redirected.

**Comment by vkku** [comment]
Adding `decimal:true`  attribute in schema solved the issue
