### ISSUE TITLE
Address not added to collection

### ISSUE THREAD

**Issue by tmess567** [tmess567/rentflees#5]
When addListing form is submitted, the address field is not populated in the collection.

**Comment by vkku** [comment]
It's working for me, check in `meteor mongo` console.
![addresscollections](https://cloud.githubusercontent.com/assets/12431831/16755672/b8ef6dd4-481c-11e6-8611-58080a13c4f4.png)

**Comment by tmess567** [comment]
It was a problem in the spelling in the template
