### ISSUE TITLE
Images are destroyed due to Heroku's ephemeral file system

### ISSUE THREAD

**Issue by tmess567** [tmess567/rentflees#6]
This app is expected to be hosted on heroku, which has an ephemeral file system which essentially means that the app will be restarted every 24 hours. This means that all uploaded files will be destroyed.

A solution to this will be to upload to one of the following:
1. A separate image hosting service
2. Rentflees.com hosting

and then link all images to that url.

**Comment by blueelvis** [comment]
We can look towards AWS S3. For the initial phase, it should be a lot cheaper.

Another option is to create a VPS with DigitalOcean in Bangalore region. That should be more than enough.

**Comment by tmess567** [comment]
For now, we have a shared hosting with which I've linked this. After a year, when our shared hosting is about to expire, we can migrate to AWS
